# Generated by Django 6.1.1 on 2026-10-04 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AddField(
            model_name='cupom',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cupom',
            name='quantidade_usos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link_afiliado', models.URLField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('is_destaque', models.BooleanField(default=False)),
                ('is_relampago', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('votos', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='plataforma.categoria')),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='plataforma.cupom')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='plataforma.loja')),
            ],
        ),
        migrations.CreateModel(
            name='favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='plataforma.oferta')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'oferta'], name='favorito_index')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'oferta'), name='unique_favorito')],
            },
        ),
        migrations.CreateModel(
            name='voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_registros', to='plataforma.oferta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'oferta'], name='voto_index')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'oferta'), name='unique_voto')],
            },
        ),
    ]
