# Generated by Django 6.1.1 on 2026-10-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_loja_alter_administrador_options_cupom_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lojaparceira',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lojaparceira',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lojaparceira',
            name='verificado',
            field=models.BooleanField(default=True),
        ),
    ]
