# Generated by Django 6.1.1 on 2026-10-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_categoria_slug_lojaparceira_logo_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
