# Generated by Django 6.1.2 on 2026-10-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_delete_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lojaparceira',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='slug',
        ),
    ]
