# Generated by Django 6.1.1 on 2026-10-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_remove_categoria_slug_remove_loja_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocao',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
