# Generated by Django 6.1.1 on 2026-10-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_promocao_descricao_promocao_imagem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='plataforma.lojaparceira'),
        ),
        migrations.RemoveIndex(
            model_name='favorito',
            name='favorito_index',
        ),
        migrations.RemoveIndex(
            model_name='voto',
            name='voto_index',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='desconto',
        ),
        migrations.AlterField(
            model_name='cupom',
            name='data_validade',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='loja',
        ),
    ]
