# Generated by Django 6.1.1 on 2026-10-08 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_oferta_loja_remove_favorito_favorito_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='duracao_horas',
            field=models.PositiveIntegerField(default=24, help_text='Por quantas horas a oferta fica no ar, a partir do cadastro.', verbose_name='Duração (horas)'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='duracao_horas',
            field=models.PositiveIntegerField(default=24, help_text='Por quantas horas a oferta fica no ar, a partir do cadastro.', verbose_name='Duração (horas)'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='data_fim',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_fim',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
