# Generated by Django 6.1.1 on 2026-10-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_oferta_duracao_horas_promocao_duracao_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='cupom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes', to='plataforma.cupom'),
        ),
    ]
