# Generated by Django 6.1.1 on 2026-10-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_promocao_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='is_relampago',
            field=models.BooleanField(default=False, verbose_name='Oferta relâmpago'),
        ),
        migrations.DeleteModel(
            name='Promocao',
        ),
    ]
