# Generated by Django 6.1.1 on 2026-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_alter_oferta_is_relampago_delete_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='quantidade_ofertas_ativas',
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
